apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: analyzer
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-analyzer
  serviceName: analyzer-0
  template:
    metadata:
      labels:
        component: reportportal-analyzer
    spec:
      containers:
#      - image: "{{ .Values.registry }}/reportportal/service-analyzer:4.1.0"
      - image: "{{ .Values.serviceanalyzer.repository }}:{{ .Values.serviceanalyzer.tag }}"
        name: analyzer
        env:
        {{ if .Values.elasticsearch.endpoint.external }}
        - name: ES_HOSTS
          value: "http://{{ default "elasticsearch" .Values.elasticsearch.endpoint.address }}:{{ default 9200 .Values.elasticsearch.endpoint.port }}"
        {{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.serviceanalyzer.resources.requests.cpu }}
            memory: {{ .Values.serviceanalyzer.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceanalyzer.resources.limits.cpu }}
            memory: {{ .Values.serviceanalyzer.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}