apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-uat
  template:
    metadata:
      labels:
        component: reportportal-uat
    spec:
      containers:
      - env:
        - name: RP_PROFILES
          value: docker
        - name: RP_SESSION_LIVE
          value: "{{ .Values.serviceauthorization.sessionLiveTime }}"
        {{ if .Values.mongodb.endpoint.external }}
        - name: RP_MONGO_DBNAME
          value: "{{ .Values.mongodb.endpoint.dbname }}"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: "{{ .Values.mongodb.endpoint.username }}"
        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.mongoSecretName }}"
              key: "mongodb-password"
        - name: "RP_MONGO_URI"
          value: "mongodb://{{ .Values.mongodb.endpoint.address }}:{{ .Values.mongodb.endpoint.port }}"
        {{- end }}
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "{{ .Values.serviceauthorization.repository }}:{{ .Values.serviceauthorization.tag }}"
        name: uat
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.serviceauthorization.resources.requests.cpu }}
            memory: {{ .Values.serviceauthorization.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceauthorization.resources.limits.cpu }}
            memory: {{ .Values.serviceauthorization.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
      tolerations:
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}