apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-ui
  template:
    metadata:
      labels:
        component: reportportal-ui
    spec:
      containers:
      - env:
        - name: RP_CONSUL.ADDRESS
          value: registry:8500
        - name: RP_CONSUL.TAGS
          value: urlprefix-/ui opts strip=/ui
        - name: RP_SERVER.PORT
          value: "8080"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "{{ .Values.serviceui.repository }}:{{ .Values.serviceui.tag }}"
        name: ui
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.serviceui.resources.requests.cpu }}
            memory: {{ .Values.serviceui.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceui.resources.limits.cpu }}
            memory: {{ .Values.serviceui.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
      tolerations:
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}