{{- if .Values.ingress.enable }}
{{- $fullName := include "reportportal.fullname" . -}}
{{- $paths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-gateway-ingress
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end}}
  rules:
{{- if .Values.ingress.usedomainname }}
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- range $svc, $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: "{{ $fullName }}-{{ $svc }}"
              servicePort: headless
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $svc, $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: "{{ $fullName }}-{{ $svc }}"
              servicePort: headless
  {{- end -}}
  {{- end -}}
  {{- end }}
status:
  loadBalancer: {}
{{- end }}
